/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.stdprofile.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-10-19")
public class StdProfile implements org.apache.thrift.TBase<StdProfile, StdProfile._Fields>, java.io.Serializable, Cloneable, Comparable<StdProfile> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("StdProfile");

  private static final org.apache.thrift.protocol.TField USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("userId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField USER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("userName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField DISPLAY_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("displayName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField PHONE_FIELD_DESC = new org.apache.thrift.protocol.TField("phone", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField EMAIL_FIELD_DESC = new org.apache.thrift.protocol.TField("email", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField GENDER_FIELD_DESC = new org.apache.thrift.protocol.TField("gender", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField OPEN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("openId", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField OPEN_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("openType", org.apache.thrift.protocol.TType.I16, (short)8);
  private static final org.apache.thrift.protocol.TField BIRTHDATE_FIELD_DESC = new org.apache.thrift.protocol.TField("birthdate", org.apache.thrift.protocol.TType.I32, (short)9);
  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)10);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.I32, (short)11);
  private static final org.apache.thrift.protocol.TField AVATAR_VERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("avatarVersion", org.apache.thrift.protocol.TType.I16, (short)12);
  private static final org.apache.thrift.protocol.TField JOINED_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("joinedTime", org.apache.thrift.protocol.TType.I32, (short)13);
  private static final org.apache.thrift.protocol.TField STATUS_TEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("statusText", org.apache.thrift.protocol.TType.STRING, (short)14);
  private static final org.apache.thrift.protocol.TField CERT_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("certDate", org.apache.thrift.protocol.TType.I32, (short)15);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new StdProfileStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new StdProfileTupleSchemeFactory();

  public int userId; // required
  public @org.apache.thrift.annotation.Nullable String userName; // required
  public @org.apache.thrift.annotation.Nullable String displayName; // required
  public long phone; // required
  public @org.apache.thrift.annotation.Nullable String email; // required
  public int gender; // required
  public @org.apache.thrift.annotation.Nullable String openId; // required
  public short openType; // required
  public int birthdate; // required
  public int type; // required
  public int status; // required
  public short avatarVersion; // required
  public int joinedTime; // required
  public @org.apache.thrift.annotation.Nullable String statusText; // optional
  public int certDate; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_ID((short)1, "userId"),
    USER_NAME((short)2, "userName"),
    DISPLAY_NAME((short)3, "displayName"),
    PHONE((short)4, "phone"),
    EMAIL((short)5, "email"),
    GENDER((short)6, "gender"),
    OPEN_ID((short)7, "openId"),
    OPEN_TYPE((short)8, "openType"),
    BIRTHDATE((short)9, "birthdate"),
    TYPE((short)10, "type"),
    STATUS((short)11, "status"),
    AVATAR_VERSION((short)12, "avatarVersion"),
    JOINED_TIME((short)13, "joinedTime"),
    STATUS_TEXT((short)14, "statusText"),
    CERT_DATE((short)15, "certDate");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_ID
          return USER_ID;
        case 2: // USER_NAME
          return USER_NAME;
        case 3: // DISPLAY_NAME
          return DISPLAY_NAME;
        case 4: // PHONE
          return PHONE;
        case 5: // EMAIL
          return EMAIL;
        case 6: // GENDER
          return GENDER;
        case 7: // OPEN_ID
          return OPEN_ID;
        case 8: // OPEN_TYPE
          return OPEN_TYPE;
        case 9: // BIRTHDATE
          return BIRTHDATE;
        case 10: // TYPE
          return TYPE;
        case 11: // STATUS
          return STATUS;
        case 12: // AVATAR_VERSION
          return AVATAR_VERSION;
        case 13: // JOINED_TIME
          return JOINED_TIME;
        case 14: // STATUS_TEXT
          return STATUS_TEXT;
        case 15: // CERT_DATE
          return CERT_DATE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __USERID_ISSET_ID = 0;
  private static final int __PHONE_ISSET_ID = 1;
  private static final int __GENDER_ISSET_ID = 2;
  private static final int __OPENTYPE_ISSET_ID = 3;
  private static final int __BIRTHDATE_ISSET_ID = 4;
  private static final int __TYPE_ISSET_ID = 5;
  private static final int __STATUS_ISSET_ID = 6;
  private static final int __AVATARVERSION_ISSET_ID = 7;
  private static final int __JOINEDTIME_ISSET_ID = 8;
  private static final int __CERTDATE_ISSET_ID = 9;
  private short __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.STATUS_TEXT,_Fields.CERT_DATE};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_ID, new org.apache.thrift.meta_data.FieldMetaData("userId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.USER_NAME, new org.apache.thrift.meta_data.FieldMetaData("userName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DISPLAY_NAME, new org.apache.thrift.meta_data.FieldMetaData("displayName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PHONE, new org.apache.thrift.meta_data.FieldMetaData("phone", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.EMAIL, new org.apache.thrift.meta_data.FieldMetaData("email", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.GENDER, new org.apache.thrift.meta_data.FieldMetaData("gender", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.OPEN_ID, new org.apache.thrift.meta_data.FieldMetaData("openId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OPEN_TYPE, new org.apache.thrift.meta_data.FieldMetaData("openType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16)));
    tmpMap.put(_Fields.BIRTHDATE, new org.apache.thrift.meta_data.FieldMetaData("birthdate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.AVATAR_VERSION, new org.apache.thrift.meta_data.FieldMetaData("avatarVersion", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16)));
    tmpMap.put(_Fields.JOINED_TIME, new org.apache.thrift.meta_data.FieldMetaData("joinedTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.STATUS_TEXT, new org.apache.thrift.meta_data.FieldMetaData("statusText", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CERT_DATE, new org.apache.thrift.meta_data.FieldMetaData("certDate", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(StdProfile.class, metaDataMap);
  }

  public StdProfile() {
  }

  public StdProfile(
    int userId,
    String userName,
    String displayName,
    long phone,
    String email,
    int gender,
    String openId,
    short openType,
    int birthdate,
    int type,
    int status,
    short avatarVersion,
    int joinedTime)
  {
    this();
    this.userId = userId;
    setUserIdIsSet(true);
    this.userName = userName;
    this.displayName = displayName;
    this.phone = phone;
    setPhoneIsSet(true);
    this.email = email;
    this.gender = gender;
    setGenderIsSet(true);
    this.openId = openId;
    this.openType = openType;
    setOpenTypeIsSet(true);
    this.birthdate = birthdate;
    setBirthdateIsSet(true);
    this.type = type;
    setTypeIsSet(true);
    this.status = status;
    setStatusIsSet(true);
    this.avatarVersion = avatarVersion;
    setAvatarVersionIsSet(true);
    this.joinedTime = joinedTime;
    setJoinedTimeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public StdProfile(StdProfile other) {
    __isset_bitfield = other.__isset_bitfield;
    this.userId = other.userId;
    if (other.isSetUserName()) {
      this.userName = other.userName;
    }
    if (other.isSetDisplayName()) {
      this.displayName = other.displayName;
    }
    this.phone = other.phone;
    if (other.isSetEmail()) {
      this.email = other.email;
    }
    this.gender = other.gender;
    if (other.isSetOpenId()) {
      this.openId = other.openId;
    }
    this.openType = other.openType;
    this.birthdate = other.birthdate;
    this.type = other.type;
    this.status = other.status;
    this.avatarVersion = other.avatarVersion;
    this.joinedTime = other.joinedTime;
    if (other.isSetStatusText()) {
      this.statusText = other.statusText;
    }
    this.certDate = other.certDate;
  }

  public StdProfile deepCopy() {
    return new StdProfile(this);
  }

  @Override
  public void clear() {
    setUserIdIsSet(false);
    this.userId = 0;
    this.userName = null;
    this.displayName = null;
    setPhoneIsSet(false);
    this.phone = 0;
    this.email = null;
    setGenderIsSet(false);
    this.gender = 0;
    this.openId = null;
    setOpenTypeIsSet(false);
    this.openType = 0;
    setBirthdateIsSet(false);
    this.birthdate = 0;
    setTypeIsSet(false);
    this.type = 0;
    setStatusIsSet(false);
    this.status = 0;
    setAvatarVersionIsSet(false);
    this.avatarVersion = 0;
    setJoinedTimeIsSet(false);
    this.joinedTime = 0;
    this.statusText = null;
    setCertDateIsSet(false);
    this.certDate = 0;
  }

  public int getUserId() {
    return this.userId;
  }

  public StdProfile setUserId(int userId) {
    this.userId = userId;
    setUserIdIsSet(true);
    return this;
  }

  public void unsetUserId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  /** Returns true if field userId is set (has been assigned a value) and false otherwise */
  public boolean isSetUserId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  public void setUserIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __USERID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public String getUserName() {
    return this.userName;
  }

  public StdProfile setUserName(@org.apache.thrift.annotation.Nullable String userName) {
    this.userName = userName;
    return this;
  }

  public void unsetUserName() {
    this.userName = null;
  }

  /** Returns true if field userName is set (has been assigned a value) and false otherwise */
  public boolean isSetUserName() {
    return this.userName != null;
  }

  public void setUserNameIsSet(boolean value) {
    if (!value) {
      this.userName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public String getDisplayName() {
    return this.displayName;
  }

  public StdProfile setDisplayName(@org.apache.thrift.annotation.Nullable String displayName) {
    this.displayName = displayName;
    return this;
  }

  public void unsetDisplayName() {
    this.displayName = null;
  }

  /** Returns true if field displayName is set (has been assigned a value) and false otherwise */
  public boolean isSetDisplayName() {
    return this.displayName != null;
  }

  public void setDisplayNameIsSet(boolean value) {
    if (!value) {
      this.displayName = null;
    }
  }

  public long getPhone() {
    return this.phone;
  }

  public StdProfile setPhone(long phone) {
    this.phone = phone;
    setPhoneIsSet(true);
    return this;
  }

  public void unsetPhone() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PHONE_ISSET_ID);
  }

  /** Returns true if field phone is set (has been assigned a value) and false otherwise */
  public boolean isSetPhone() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PHONE_ISSET_ID);
  }

  public void setPhoneIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PHONE_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public String getEmail() {
    return this.email;
  }

  public StdProfile setEmail(@org.apache.thrift.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  public void unsetEmail() {
    this.email = null;
  }

  /** Returns true if field email is set (has been assigned a value) and false otherwise */
  public boolean isSetEmail() {
    return this.email != null;
  }

  public void setEmailIsSet(boolean value) {
    if (!value) {
      this.email = null;
    }
  }

  public int getGender() {
    return this.gender;
  }

  public StdProfile setGender(int gender) {
    this.gender = gender;
    setGenderIsSet(true);
    return this;
  }

  public void unsetGender() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __GENDER_ISSET_ID);
  }

  /** Returns true if field gender is set (has been assigned a value) and false otherwise */
  public boolean isSetGender() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __GENDER_ISSET_ID);
  }

  public void setGenderIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __GENDER_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public String getOpenId() {
    return this.openId;
  }

  public StdProfile setOpenId(@org.apache.thrift.annotation.Nullable String openId) {
    this.openId = openId;
    return this;
  }

  public void unsetOpenId() {
    this.openId = null;
  }

  /** Returns true if field openId is set (has been assigned a value) and false otherwise */
  public boolean isSetOpenId() {
    return this.openId != null;
  }

  public void setOpenIdIsSet(boolean value) {
    if (!value) {
      this.openId = null;
    }
  }

  public short getOpenType() {
    return this.openType;
  }

  public StdProfile setOpenType(short openType) {
    this.openType = openType;
    setOpenTypeIsSet(true);
    return this;
  }

  public void unsetOpenType() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __OPENTYPE_ISSET_ID);
  }

  /** Returns true if field openType is set (has been assigned a value) and false otherwise */
  public boolean isSetOpenType() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __OPENTYPE_ISSET_ID);
  }

  public void setOpenTypeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __OPENTYPE_ISSET_ID, value);
  }

  public int getBirthdate() {
    return this.birthdate;
  }

  public StdProfile setBirthdate(int birthdate) {
    this.birthdate = birthdate;
    setBirthdateIsSet(true);
    return this;
  }

  public void unsetBirthdate() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BIRTHDATE_ISSET_ID);
  }

  /** Returns true if field birthdate is set (has been assigned a value) and false otherwise */
  public boolean isSetBirthdate() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BIRTHDATE_ISSET_ID);
  }

  public void setBirthdateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BIRTHDATE_ISSET_ID, value);
  }

  public int getType() {
    return this.type;
  }

  public StdProfile setType(int type) {
    this.type = type;
    setTypeIsSet(true);
    return this;
  }

  public void unsetType() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TYPE_ISSET_ID);
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TYPE_ISSET_ID);
  }

  public void setTypeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TYPE_ISSET_ID, value);
  }

  public int getStatus() {
    return this.status;
  }

  public StdProfile setStatus(int status) {
    this.status = status;
    setStatusIsSet(true);
    return this;
  }

  public void unsetStatus() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  public void setStatusIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STATUS_ISSET_ID, value);
  }

  public short getAvatarVersion() {
    return this.avatarVersion;
  }

  public StdProfile setAvatarVersion(short avatarVersion) {
    this.avatarVersion = avatarVersion;
    setAvatarVersionIsSet(true);
    return this;
  }

  public void unsetAvatarVersion() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __AVATARVERSION_ISSET_ID);
  }

  /** Returns true if field avatarVersion is set (has been assigned a value) and false otherwise */
  public boolean isSetAvatarVersion() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __AVATARVERSION_ISSET_ID);
  }

  public void setAvatarVersionIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __AVATARVERSION_ISSET_ID, value);
  }

  public int getJoinedTime() {
    return this.joinedTime;
  }

  public StdProfile setJoinedTime(int joinedTime) {
    this.joinedTime = joinedTime;
    setJoinedTimeIsSet(true);
    return this;
  }

  public void unsetJoinedTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __JOINEDTIME_ISSET_ID);
  }

  /** Returns true if field joinedTime is set (has been assigned a value) and false otherwise */
  public boolean isSetJoinedTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __JOINEDTIME_ISSET_ID);
  }

  public void setJoinedTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __JOINEDTIME_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public String getStatusText() {
    return this.statusText;
  }

  public StdProfile setStatusText(@org.apache.thrift.annotation.Nullable String statusText) {
    this.statusText = statusText;
    return this;
  }

  public void unsetStatusText() {
    this.statusText = null;
  }

  /** Returns true if field statusText is set (has been assigned a value) and false otherwise */
  public boolean isSetStatusText() {
    return this.statusText != null;
  }

  public void setStatusTextIsSet(boolean value) {
    if (!value) {
      this.statusText = null;
    }
  }

  public int getCertDate() {
    return this.certDate;
  }

  public StdProfile setCertDate(int certDate) {
    this.certDate = certDate;
    setCertDateIsSet(true);
    return this;
  }

  public void unsetCertDate() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CERTDATE_ISSET_ID);
  }

  /** Returns true if field certDate is set (has been assigned a value) and false otherwise */
  public boolean isSetCertDate() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CERTDATE_ISSET_ID);
  }

  public void setCertDateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CERTDATE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case USER_ID:
      if (value == null) {
        unsetUserId();
      } else {
        setUserId((Integer)value);
      }
      break;

    case USER_NAME:
      if (value == null) {
        unsetUserName();
      } else {
        setUserName((String)value);
      }
      break;

    case DISPLAY_NAME:
      if (value == null) {
        unsetDisplayName();
      } else {
        setDisplayName((String)value);
      }
      break;

    case PHONE:
      if (value == null) {
        unsetPhone();
      } else {
        setPhone((Long)value);
      }
      break;

    case EMAIL:
      if (value == null) {
        unsetEmail();
      } else {
        setEmail((String)value);
      }
      break;

    case GENDER:
      if (value == null) {
        unsetGender();
      } else {
        setGender((Integer)value);
      }
      break;

    case OPEN_ID:
      if (value == null) {
        unsetOpenId();
      } else {
        setOpenId((String)value);
      }
      break;

    case OPEN_TYPE:
      if (value == null) {
        unsetOpenType();
      } else {
        setOpenType((Short)value);
      }
      break;

    case BIRTHDATE:
      if (value == null) {
        unsetBirthdate();
      } else {
        setBirthdate((Integer)value);
      }
      break;

    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((Integer)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((Integer)value);
      }
      break;

    case AVATAR_VERSION:
      if (value == null) {
        unsetAvatarVersion();
      } else {
        setAvatarVersion((Short)value);
      }
      break;

    case JOINED_TIME:
      if (value == null) {
        unsetJoinedTime();
      } else {
        setJoinedTime((Integer)value);
      }
      break;

    case STATUS_TEXT:
      if (value == null) {
        unsetStatusText();
      } else {
        setStatusText((String)value);
      }
      break;

    case CERT_DATE:
      if (value == null) {
        unsetCertDate();
      } else {
        setCertDate((Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case USER_ID:
      return getUserId();

    case USER_NAME:
      return getUserName();

    case DISPLAY_NAME:
      return getDisplayName();

    case PHONE:
      return getPhone();

    case EMAIL:
      return getEmail();

    case GENDER:
      return getGender();

    case OPEN_ID:
      return getOpenId();

    case OPEN_TYPE:
      return getOpenType();

    case BIRTHDATE:
      return getBirthdate();

    case TYPE:
      return getType();

    case STATUS:
      return getStatus();

    case AVATAR_VERSION:
      return getAvatarVersion();

    case JOINED_TIME:
      return getJoinedTime();

    case STATUS_TEXT:
      return getStatusText();

    case CERT_DATE:
      return getCertDate();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case USER_ID:
      return isSetUserId();
    case USER_NAME:
      return isSetUserName();
    case DISPLAY_NAME:
      return isSetDisplayName();
    case PHONE:
      return isSetPhone();
    case EMAIL:
      return isSetEmail();
    case GENDER:
      return isSetGender();
    case OPEN_ID:
      return isSetOpenId();
    case OPEN_TYPE:
      return isSetOpenType();
    case BIRTHDATE:
      return isSetBirthdate();
    case TYPE:
      return isSetType();
    case STATUS:
      return isSetStatus();
    case AVATAR_VERSION:
      return isSetAvatarVersion();
    case JOINED_TIME:
      return isSetJoinedTime();
    case STATUS_TEXT:
      return isSetStatusText();
    case CERT_DATE:
      return isSetCertDate();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof StdProfile)
      return this.equals((StdProfile)that);
    return false;
  }

  public boolean equals(StdProfile that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_userId = true;
    boolean that_present_userId = true;
    if (this_present_userId || that_present_userId) {
      if (!(this_present_userId && that_present_userId))
        return false;
      if (this.userId != that.userId)
        return false;
    }

    boolean this_present_userName = true && this.isSetUserName();
    boolean that_present_userName = true && that.isSetUserName();
    if (this_present_userName || that_present_userName) {
      if (!(this_present_userName && that_present_userName))
        return false;
      if (!this.userName.equals(that.userName))
        return false;
    }

    boolean this_present_displayName = true && this.isSetDisplayName();
    boolean that_present_displayName = true && that.isSetDisplayName();
    if (this_present_displayName || that_present_displayName) {
      if (!(this_present_displayName && that_present_displayName))
        return false;
      if (!this.displayName.equals(that.displayName))
        return false;
    }

    boolean this_present_phone = true;
    boolean that_present_phone = true;
    if (this_present_phone || that_present_phone) {
      if (!(this_present_phone && that_present_phone))
        return false;
      if (this.phone != that.phone)
        return false;
    }

    boolean this_present_email = true && this.isSetEmail();
    boolean that_present_email = true && that.isSetEmail();
    if (this_present_email || that_present_email) {
      if (!(this_present_email && that_present_email))
        return false;
      if (!this.email.equals(that.email))
        return false;
    }

    boolean this_present_gender = true;
    boolean that_present_gender = true;
    if (this_present_gender || that_present_gender) {
      if (!(this_present_gender && that_present_gender))
        return false;
      if (this.gender != that.gender)
        return false;
    }

    boolean this_present_openId = true && this.isSetOpenId();
    boolean that_present_openId = true && that.isSetOpenId();
    if (this_present_openId || that_present_openId) {
      if (!(this_present_openId && that_present_openId))
        return false;
      if (!this.openId.equals(that.openId))
        return false;
    }

    boolean this_present_openType = true;
    boolean that_present_openType = true;
    if (this_present_openType || that_present_openType) {
      if (!(this_present_openType && that_present_openType))
        return false;
      if (this.openType != that.openType)
        return false;
    }

    boolean this_present_birthdate = true;
    boolean that_present_birthdate = true;
    if (this_present_birthdate || that_present_birthdate) {
      if (!(this_present_birthdate && that_present_birthdate))
        return false;
      if (this.birthdate != that.birthdate)
        return false;
    }

    boolean this_present_type = true;
    boolean that_present_type = true;
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (this.type != that.type)
        return false;
    }

    boolean this_present_status = true;
    boolean that_present_status = true;
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (this.status != that.status)
        return false;
    }

    boolean this_present_avatarVersion = true;
    boolean that_present_avatarVersion = true;
    if (this_present_avatarVersion || that_present_avatarVersion) {
      if (!(this_present_avatarVersion && that_present_avatarVersion))
        return false;
      if (this.avatarVersion != that.avatarVersion)
        return false;
    }

    boolean this_present_joinedTime = true;
    boolean that_present_joinedTime = true;
    if (this_present_joinedTime || that_present_joinedTime) {
      if (!(this_present_joinedTime && that_present_joinedTime))
        return false;
      if (this.joinedTime != that.joinedTime)
        return false;
    }

    boolean this_present_statusText = true && this.isSetStatusText();
    boolean that_present_statusText = true && that.isSetStatusText();
    if (this_present_statusText || that_present_statusText) {
      if (!(this_present_statusText && that_present_statusText))
        return false;
      if (!this.statusText.equals(that.statusText))
        return false;
    }

    boolean this_present_certDate = true && this.isSetCertDate();
    boolean that_present_certDate = true && that.isSetCertDate();
    if (this_present_certDate || that_present_certDate) {
      if (!(this_present_certDate && that_present_certDate))
        return false;
      if (this.certDate != that.certDate)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + userId;

    hashCode = hashCode * 8191 + ((isSetUserName()) ? 131071 : 524287);
    if (isSetUserName())
      hashCode = hashCode * 8191 + userName.hashCode();

    hashCode = hashCode * 8191 + ((isSetDisplayName()) ? 131071 : 524287);
    if (isSetDisplayName())
      hashCode = hashCode * 8191 + displayName.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(phone);

    hashCode = hashCode * 8191 + ((isSetEmail()) ? 131071 : 524287);
    if (isSetEmail())
      hashCode = hashCode * 8191 + email.hashCode();

    hashCode = hashCode * 8191 + gender;

    hashCode = hashCode * 8191 + ((isSetOpenId()) ? 131071 : 524287);
    if (isSetOpenId())
      hashCode = hashCode * 8191 + openId.hashCode();

    hashCode = hashCode * 8191 + openType;

    hashCode = hashCode * 8191 + birthdate;

    hashCode = hashCode * 8191 + type;

    hashCode = hashCode * 8191 + status;

    hashCode = hashCode * 8191 + avatarVersion;

    hashCode = hashCode * 8191 + joinedTime;

    hashCode = hashCode * 8191 + ((isSetStatusText()) ? 131071 : 524287);
    if (isSetStatusText())
      hashCode = hashCode * 8191 + statusText.hashCode();

    hashCode = hashCode * 8191 + ((isSetCertDate()) ? 131071 : 524287);
    if (isSetCertDate())
      hashCode = hashCode * 8191 + certDate;

    return hashCode;
  }

  @Override
  public int compareTo(StdProfile other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUserId()).compareTo(other.isSetUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userId, other.userId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUserName()).compareTo(other.isSetUserName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userName, other.userName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDisplayName()).compareTo(other.isSetDisplayName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDisplayName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.displayName, other.displayName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPhone()).compareTo(other.isSetPhone());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPhone()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.phone, other.phone);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEmail()).compareTo(other.isSetEmail());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEmail()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.email, other.email);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetGender()).compareTo(other.isSetGender());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGender()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gender, other.gender);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOpenId()).compareTo(other.isSetOpenId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOpenId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.openId, other.openId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOpenType()).compareTo(other.isSetOpenType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOpenType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.openType, other.openType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBirthdate()).compareTo(other.isSetBirthdate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBirthdate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.birthdate, other.birthdate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetType()).compareTo(other.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, other.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, other.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAvatarVersion()).compareTo(other.isSetAvatarVersion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAvatarVersion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.avatarVersion, other.avatarVersion);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetJoinedTime()).compareTo(other.isSetJoinedTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJoinedTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.joinedTime, other.joinedTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStatusText()).compareTo(other.isSetStatusText());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatusText()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.statusText, other.statusText);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCertDate()).compareTo(other.isSetCertDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCertDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.certDate, other.certDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("StdProfile(");
    boolean first = true;

    sb.append("userId:");
    sb.append(this.userId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("userName:");
    if (this.userName == null) {
      sb.append("null");
    } else {
      sb.append(this.userName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("displayName:");
    if (this.displayName == null) {
      sb.append("null");
    } else {
      sb.append(this.displayName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("phone:");
    sb.append(this.phone);
    first = false;
    if (!first) sb.append(", ");
    sb.append("email:");
    if (this.email == null) {
      sb.append("null");
    } else {
      sb.append(this.email);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("gender:");
    sb.append(this.gender);
    first = false;
    if (!first) sb.append(", ");
    sb.append("openId:");
    if (this.openId == null) {
      sb.append("null");
    } else {
      sb.append(this.openId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("openType:");
    sb.append(this.openType);
    first = false;
    if (!first) sb.append(", ");
    sb.append("birthdate:");
    sb.append(this.birthdate);
    first = false;
    if (!first) sb.append(", ");
    sb.append("type:");
    sb.append(this.type);
    first = false;
    if (!first) sb.append(", ");
    sb.append("status:");
    sb.append(this.status);
    first = false;
    if (!first) sb.append(", ");
    sb.append("avatarVersion:");
    sb.append(this.avatarVersion);
    first = false;
    if (!first) sb.append(", ");
    sb.append("joinedTime:");
    sb.append(this.joinedTime);
    first = false;
    if (isSetStatusText()) {
      if (!first) sb.append(", ");
      sb.append("statusText:");
      if (this.statusText == null) {
        sb.append("null");
      } else {
        sb.append(this.statusText);
      }
      first = false;
    }
    if (isSetCertDate()) {
      if (!first) sb.append(", ");
      sb.append("certDate:");
      sb.append(this.certDate);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class StdProfileStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public StdProfileStandardScheme getScheme() {
      return new StdProfileStandardScheme();
    }
  }

  private static class StdProfileStandardScheme extends org.apache.thrift.scheme.StandardScheme<StdProfile> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, StdProfile struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.userId = iprot.readI32();
              struct.setUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // USER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.userName = iprot.readString();
              struct.setUserNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DISPLAY_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.displayName = iprot.readString();
              struct.setDisplayNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PHONE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.phone = iprot.readI64();
              struct.setPhoneIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // EMAIL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.email = iprot.readString();
              struct.setEmailIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // GENDER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.gender = iprot.readI32();
              struct.setGenderIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // OPEN_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.openId = iprot.readString();
              struct.setOpenIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // OPEN_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.openType = iprot.readI16();
              struct.setOpenTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // BIRTHDATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.birthdate = iprot.readI32();
              struct.setBirthdateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type = iprot.readI32();
              struct.setTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status = iprot.readI32();
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // AVATAR_VERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.avatarVersion = iprot.readI16();
              struct.setAvatarVersionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // JOINED_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.joinedTime = iprot.readI32();
              struct.setJoinedTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // STATUS_TEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.statusText = iprot.readString();
              struct.setStatusTextIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // CERT_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.certDate = iprot.readI32();
              struct.setCertDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, StdProfile struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(USER_ID_FIELD_DESC);
      oprot.writeI32(struct.userId);
      oprot.writeFieldEnd();
      if (struct.userName != null) {
        oprot.writeFieldBegin(USER_NAME_FIELD_DESC);
        oprot.writeString(struct.userName);
        oprot.writeFieldEnd();
      }
      if (struct.displayName != null) {
        oprot.writeFieldBegin(DISPLAY_NAME_FIELD_DESC);
        oprot.writeString(struct.displayName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PHONE_FIELD_DESC);
      oprot.writeI64(struct.phone);
      oprot.writeFieldEnd();
      if (struct.email != null) {
        oprot.writeFieldBegin(EMAIL_FIELD_DESC);
        oprot.writeString(struct.email);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(GENDER_FIELD_DESC);
      oprot.writeI32(struct.gender);
      oprot.writeFieldEnd();
      if (struct.openId != null) {
        oprot.writeFieldBegin(OPEN_ID_FIELD_DESC);
        oprot.writeString(struct.openId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(OPEN_TYPE_FIELD_DESC);
      oprot.writeI16(struct.openType);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BIRTHDATE_FIELD_DESC);
      oprot.writeI32(struct.birthdate);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TYPE_FIELD_DESC);
      oprot.writeI32(struct.type);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(STATUS_FIELD_DESC);
      oprot.writeI32(struct.status);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(AVATAR_VERSION_FIELD_DESC);
      oprot.writeI16(struct.avatarVersion);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(JOINED_TIME_FIELD_DESC);
      oprot.writeI32(struct.joinedTime);
      oprot.writeFieldEnd();
      if (struct.statusText != null) {
        if (struct.isSetStatusText()) {
          oprot.writeFieldBegin(STATUS_TEXT_FIELD_DESC);
          oprot.writeString(struct.statusText);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetCertDate()) {
        oprot.writeFieldBegin(CERT_DATE_FIELD_DESC);
        oprot.writeI32(struct.certDate);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class StdProfileTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public StdProfileTupleScheme getScheme() {
      return new StdProfileTupleScheme();
    }
  }

  private static class StdProfileTupleScheme extends org.apache.thrift.scheme.TupleScheme<StdProfile> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, StdProfile struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetUserId()) {
        optionals.set(0);
      }
      if (struct.isSetUserName()) {
        optionals.set(1);
      }
      if (struct.isSetDisplayName()) {
        optionals.set(2);
      }
      if (struct.isSetPhone()) {
        optionals.set(3);
      }
      if (struct.isSetEmail()) {
        optionals.set(4);
      }
      if (struct.isSetGender()) {
        optionals.set(5);
      }
      if (struct.isSetOpenId()) {
        optionals.set(6);
      }
      if (struct.isSetOpenType()) {
        optionals.set(7);
      }
      if (struct.isSetBirthdate()) {
        optionals.set(8);
      }
      if (struct.isSetType()) {
        optionals.set(9);
      }
      if (struct.isSetStatus()) {
        optionals.set(10);
      }
      if (struct.isSetAvatarVersion()) {
        optionals.set(11);
      }
      if (struct.isSetJoinedTime()) {
        optionals.set(12);
      }
      if (struct.isSetStatusText()) {
        optionals.set(13);
      }
      if (struct.isSetCertDate()) {
        optionals.set(14);
      }
      oprot.writeBitSet(optionals, 15);
      if (struct.isSetUserId()) {
        oprot.writeI32(struct.userId);
      }
      if (struct.isSetUserName()) {
        oprot.writeString(struct.userName);
      }
      if (struct.isSetDisplayName()) {
        oprot.writeString(struct.displayName);
      }
      if (struct.isSetPhone()) {
        oprot.writeI64(struct.phone);
      }
      if (struct.isSetEmail()) {
        oprot.writeString(struct.email);
      }
      if (struct.isSetGender()) {
        oprot.writeI32(struct.gender);
      }
      if (struct.isSetOpenId()) {
        oprot.writeString(struct.openId);
      }
      if (struct.isSetOpenType()) {
        oprot.writeI16(struct.openType);
      }
      if (struct.isSetBirthdate()) {
        oprot.writeI32(struct.birthdate);
      }
      if (struct.isSetType()) {
        oprot.writeI32(struct.type);
      }
      if (struct.isSetStatus()) {
        oprot.writeI32(struct.status);
      }
      if (struct.isSetAvatarVersion()) {
        oprot.writeI16(struct.avatarVersion);
      }
      if (struct.isSetJoinedTime()) {
        oprot.writeI32(struct.joinedTime);
      }
      if (struct.isSetStatusText()) {
        oprot.writeString(struct.statusText);
      }
      if (struct.isSetCertDate()) {
        oprot.writeI32(struct.certDate);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, StdProfile struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(15);
      if (incoming.get(0)) {
        struct.userId = iprot.readI32();
        struct.setUserIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.userName = iprot.readString();
        struct.setUserNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.displayName = iprot.readString();
        struct.setDisplayNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.phone = iprot.readI64();
        struct.setPhoneIsSet(true);
      }
      if (incoming.get(4)) {
        struct.email = iprot.readString();
        struct.setEmailIsSet(true);
      }
      if (incoming.get(5)) {
        struct.gender = iprot.readI32();
        struct.setGenderIsSet(true);
      }
      if (incoming.get(6)) {
        struct.openId = iprot.readString();
        struct.setOpenIdIsSet(true);
      }
      if (incoming.get(7)) {
        struct.openType = iprot.readI16();
        struct.setOpenTypeIsSet(true);
      }
      if (incoming.get(8)) {
        struct.birthdate = iprot.readI32();
        struct.setBirthdateIsSet(true);
      }
      if (incoming.get(9)) {
        struct.type = iprot.readI32();
        struct.setTypeIsSet(true);
      }
      if (incoming.get(10)) {
        struct.status = iprot.readI32();
        struct.setStatusIsSet(true);
      }
      if (incoming.get(11)) {
        struct.avatarVersion = iprot.readI16();
        struct.setAvatarVersionIsSet(true);
      }
      if (incoming.get(12)) {
        struct.joinedTime = iprot.readI32();
        struct.setJoinedTimeIsSet(true);
      }
      if (incoming.get(13)) {
        struct.statusText = iprot.readString();
        struct.setStatusTextIsSet(true);
      }
      if (incoming.get(14)) {
        struct.certDate = iprot.readI32();
        struct.setCertDateIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

