/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sbizprofile.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2021-01-04")
public class MapSbizProfileResult implements org.apache.thrift.TBase<MapSbizProfileResult, MapSbizProfileResult._Fields>, java.io.Serializable, Cloneable, Comparable<MapSbizProfileResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MapSbizProfileResult");

  private static final org.apache.thrift.protocol.TField ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("error", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField DATA_MAP_FIELD_DESC = new org.apache.thrift.protocol.TField("dataMap", org.apache.thrift.protocol.TType.MAP, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MapSbizProfileResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MapSbizProfileResultTupleSchemeFactory();

  public int error; // required
  public @org.apache.thrift.annotation.Nullable java.util.Map<Integer,SbizProfile> dataMap; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ERROR((short)1, "error"),
    DATA_MAP((short)2, "dataMap");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ERROR
          return ERROR;
        case 2: // DATA_MAP
          return DATA_MAP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ERROR_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ERROR, new org.apache.thrift.meta_data.FieldMetaData("error", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DATA_MAP, new org.apache.thrift.meta_data.FieldMetaData("dataMap", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SbizProfile.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MapSbizProfileResult.class, metaDataMap);
  }

  public MapSbizProfileResult() {
  }

  public MapSbizProfileResult(
    int error,
    java.util.Map<Integer,SbizProfile> dataMap)
  {
    this();
    this.error = error;
    setErrorIsSet(true);
    this.dataMap = dataMap;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MapSbizProfileResult(MapSbizProfileResult other) {
    __isset_bitfield = other.__isset_bitfield;
    this.error = other.error;
    if (other.isSetDataMap()) {
      java.util.Map<Integer,SbizProfile> __this__dataMap = new java.util.HashMap<Integer,SbizProfile>(other.dataMap.size());
      for (java.util.Map.Entry<Integer, SbizProfile> other_element : other.dataMap.entrySet()) {

        Integer other_element_key = other_element.getKey();
        SbizProfile other_element_value = other_element.getValue();

        Integer __this__dataMap_copy_key = other_element_key;

        SbizProfile __this__dataMap_copy_value = new SbizProfile(other_element_value);

        __this__dataMap.put(__this__dataMap_copy_key, __this__dataMap_copy_value);
      }
      this.dataMap = __this__dataMap;
    }
  }

  public MapSbizProfileResult deepCopy() {
    return new MapSbizProfileResult(this);
  }

  @Override
  public void clear() {
    setErrorIsSet(false);
    this.error = 0;
    this.dataMap = null;
  }

  public int getError() {
    return this.error;
  }

  public MapSbizProfileResult setError(int error) {
    this.error = error;
    setErrorIsSet(true);
    return this;
  }

  public void unsetError() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ERROR_ISSET_ID);
  }

  /** Returns true if field error is set (has been assigned a value) and false otherwise */
  public boolean isSetError() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ERROR_ISSET_ID);
  }

  public void setErrorIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ERROR_ISSET_ID, value);
  }

  public int getDataMapSize() {
    return (this.dataMap == null) ? 0 : this.dataMap.size();
  }

  public void putToDataMap(int key, SbizProfile val) {
    if (this.dataMap == null) {
      this.dataMap = new java.util.HashMap<Integer,SbizProfile>();
    }
    this.dataMap.put(key, val);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Map<Integer,SbizProfile> getDataMap() {
    return this.dataMap;
  }

  public MapSbizProfileResult setDataMap(@org.apache.thrift.annotation.Nullable java.util.Map<Integer,SbizProfile> dataMap) {
    this.dataMap = dataMap;
    return this;
  }

  public void unsetDataMap() {
    this.dataMap = null;
  }

  /** Returns true if field dataMap is set (has been assigned a value) and false otherwise */
  public boolean isSetDataMap() {
    return this.dataMap != null;
  }

  public void setDataMapIsSet(boolean value) {
    if (!value) {
      this.dataMap = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case ERROR:
      if (value == null) {
        unsetError();
      } else {
        setError((Integer)value);
      }
      break;

    case DATA_MAP:
      if (value == null) {
        unsetDataMap();
      } else {
        setDataMap((java.util.Map<Integer,SbizProfile>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ERROR:
      return getError();

    case DATA_MAP:
      return getDataMap();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ERROR:
      return isSetError();
    case DATA_MAP:
      return isSetDataMap();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MapSbizProfileResult)
      return this.equals((MapSbizProfileResult)that);
    return false;
  }

  public boolean equals(MapSbizProfileResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_error = true;
    boolean that_present_error = true;
    if (this_present_error || that_present_error) {
      if (!(this_present_error && that_present_error))
        return false;
      if (this.error != that.error)
        return false;
    }

    boolean this_present_dataMap = true && this.isSetDataMap();
    boolean that_present_dataMap = true && that.isSetDataMap();
    if (this_present_dataMap || that_present_dataMap) {
      if (!(this_present_dataMap && that_present_dataMap))
        return false;
      if (!this.dataMap.equals(that.dataMap))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + error;

    hashCode = hashCode * 8191 + ((isSetDataMap()) ? 131071 : 524287);
    if (isSetDataMap())
      hashCode = hashCode * 8191 + dataMap.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(MapSbizProfileResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetError()).compareTo(other.isSetError());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error, other.error);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDataMap()).compareTo(other.isSetDataMap());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDataMap()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dataMap, other.dataMap);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MapSbizProfileResult(");
    boolean first = true;

    sb.append("error:");
    sb.append(this.error);
    first = false;
    if (!first) sb.append(", ");
    sb.append("dataMap:");
    if (this.dataMap == null) {
      sb.append("null");
    } else {
      sb.append(this.dataMap);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MapSbizProfileResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MapSbizProfileResultStandardScheme getScheme() {
      return new MapSbizProfileResultStandardScheme();
    }
  }

  private static class MapSbizProfileResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<MapSbizProfileResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MapSbizProfileResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ERROR
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.error = iprot.readI32();
              struct.setErrorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DATA_MAP
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.dataMap = new java.util.HashMap<Integer,SbizProfile>(2*_map0.size);
                int _key1;
                @org.apache.thrift.annotation.Nullable SbizProfile _val2;
                for (int _i3 = 0; _i3 < _map0.size; ++_i3)
                {
                  _key1 = iprot.readI32();
                  _val2 = new SbizProfile();
                  _val2.read(iprot);
                  struct.dataMap.put(_key1, _val2);
                }
                iprot.readMapEnd();
              }
              struct.setDataMapIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MapSbizProfileResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ERROR_FIELD_DESC);
      oprot.writeI32(struct.error);
      oprot.writeFieldEnd();
      if (struct.dataMap != null) {
        oprot.writeFieldBegin(DATA_MAP_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT, struct.dataMap.size()));
          for (java.util.Map.Entry<Integer, SbizProfile> _iter4 : struct.dataMap.entrySet())
          {
            oprot.writeI32(_iter4.getKey());
            _iter4.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MapSbizProfileResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MapSbizProfileResultTupleScheme getScheme() {
      return new MapSbizProfileResultTupleScheme();
    }
  }

  private static class MapSbizProfileResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<MapSbizProfileResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MapSbizProfileResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetError()) {
        optionals.set(0);
      }
      if (struct.isSetDataMap()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetError()) {
        oprot.writeI32(struct.error);
      }
      if (struct.isSetDataMap()) {
        {
          oprot.writeI32(struct.dataMap.size());
          for (java.util.Map.Entry<Integer, SbizProfile> _iter5 : struct.dataMap.entrySet())
          {
            oprot.writeI32(_iter5.getKey());
            _iter5.getValue().write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MapSbizProfileResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.error = iprot.readI32();
        struct.setErrorIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TMap _map6 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.dataMap = new java.util.HashMap<Integer,SbizProfile>(2*_map6.size);
          int _key7;
          @org.apache.thrift.annotation.Nullable SbizProfile _val8;
          for (int _i9 = 0; _i9 < _map6.size; ++_i9)
          {
            _key7 = iprot.readI32();
            _val8 = new SbizProfile();
            _val8.read(iprot);
            struct.dataMap.put(_key7, _val8);
          }
        }
        struct.setDataMapIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

