// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gift.proto

package gift;

public interface ClaimGiftRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gift.ClaimGiftRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 serverId = 1;</code>
   */
  int getServerId();

  /**
   * <code>int32 userId = 2;</code>
   */
  int getUserId();

  /**
   * <code>string giftCode = 3;</code>
   */
  java.lang.String getGiftCode();
  /**
   * <code>string giftCode = 3;</code>
   */
  com.google.protobuf.ByteString
      getGiftCodeBytes();
}
