// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gift.proto

package gift;

public interface ClaimGiftResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gift.ClaimGiftResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>string rewardFormat = 2;</code>
   */
  java.lang.String getRewardFormat();
  /**
   * <code>string rewardFormat = 2;</code>
   */
  com.google.protobuf.ByteString
      getRewardFormatBytes();
}
