// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gift.proto

package gift;

public final class GiftService {
  private GiftService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gift_ClaimGiftRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gift_ClaimGiftRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gift_ClaimGiftResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gift_ClaimGiftResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gift_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gift_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gift_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gift_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngift.proto\022\004gift\"F\n\020ClaimGiftRequest\022\020" +
      "\n\010serverId\030\001 \001(\005\022\016\n\006userId\030\002 \001(\005\022\020\n\010gift" +
      "Code\030\003 \001(\t\"6\n\021ClaimGiftResponse\022\013\n\003msg\030\001" +
      " \001(\t\022\024\n\014rewardFormat\030\002 \001(\t\"\034\n\014HelloReque" +
      "st\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007messag" +
      "e\030\001 \001(\t2z\n\004Gift\0222\n\010SayHello\022\022.gift.Hello" +
      "Request\032\020.gift.HelloReply\"\000\022>\n\tClaimGift" +
      "\022\026.gift.ClaimGiftRequest\032\027.gift.ClaimGif" +
      "tResponse\"\000B\025\n\004giftB\013GiftServiceP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gift_ClaimGiftRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gift_ClaimGiftRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gift_ClaimGiftRequest_descriptor,
        new java.lang.String[] { "ServerId", "UserId", "GiftCode", });
    internal_static_gift_ClaimGiftResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gift_ClaimGiftResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gift_ClaimGiftResponse_descriptor,
        new java.lang.String[] { "Msg", "RewardFormat", });
    internal_static_gift_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gift_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gift_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_gift_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gift_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gift_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
